### ISSUE TITLE
Text inputs lose their focus when pressing Alt in example1

### ISSUE THREAD

**Issue by FreeSlave** [buggins/dlangui#215]
Alt key emphasizes menu so text input loses their focus. Focus gets back after Alt is pressed again. At least on Linux.

Also Alt + *Letter* does not open menus in example1.

About shortcut guides generally: it seems like on Linux shortcut letters are always emphasized (in Qt and GTK applications), while in typical Windows applications - only when pressing Alt.  Not sure if there're guidelines on this behavior for each platform.

**Comment by buggins** [comment]
It's working as designed.
ALT press + release moves focus to MainMenu. Now you can choose some menu item with arrows. Pressing ALT again restores previous focus.
Try compare to behavior of some Windows app.
I think it's not a bug.

**Comment by MyLittleRobo** [comment]
Just tried in notepad.exe. Alt grabs focus, but it's restored after I start other input, not only Alt. (The first character is lost though in order to restore focus)
While in dlangui the only way to restore focus is pressing the Alt again.

On Linux apps usually does not grabs focus by Alt at all, so when you start input all characters are written to text input, without losing the first character.

**Comment by MyLittleRobo** [comment]
Note: I described notepad behavior on Windows 8.1 Other versions can behave differently.
Strangely MS Paint, Wordpad and Qt applications on Windows behave like you described though (restore focus only on pressing Alt again). Maybe notepad is some exception.

GTK applications on Windows behave like they are on Linux not grabbing focus at all.

No matter what behavior you will choose for Windows, there're two issues to fix: 

1. Linux version should not grab focus.
2. Alt + Letter shortcuts don't work on Linux neither on Windows.

**Comment by buggins** [comment]
Fix is made to process single Alt keypress as main menu activation to work only under Windows.
