### ISSUE TITLE
Use of native controls is impossible for now?

### ISSUE THREAD

**Issue by denizzzka** [buggins/dlangui#389]
`class Button : Widget` is not contains ability to draw native Button (its `onDraw` only draws background and displays text).

This works for SDL platform, for consoles etc. But if we need to show native widget it is unacceptable.

**Comment by and3md** [comment]
DlangUI not uses native controls. If you want widgets to look like native just make your own theme.

**Comment by buggins** [comment]
I think it doesn't make sense to add native controls. And it's too hard to implement.
Custom theme can help to make almost native look&feel.

**Comment by denizzzka** [comment]
>  And it's too hard to implement.

Why?

> Custom theme can help to make almost native look&feel.

Every GUI library provide _almost_ native look&feel...

**Comment by and3md** [comment]
> Why?

Use of native widgets needs not only a lot of time to wrote but also a lot of resources for maintain. For example simple situation - new version of native widgets api and a lot of things needs be rewritten and tested again.

But that makes more work also to **you** when you write app using widgetset that use native widgets for different platforms. You need then test every platform and make a lot of **if**s because some things looks good on platform A  but looks bad on platform B. 

Support for that app will be more complicated too (example: casual people often don't know what system they have and then try explain how to open file when file dialog looks different on different platforms).

Native widgets on different platforms has its **own limitations** so you need implement/maintain a list of features that are cross platform and emulate some thing on others. 

Big widgetsets do the same - for example QT draws widgets itself.

**Comment by denizzzka** [comment]
> Use of native widgets needs not only a lot of time to wrote but also a lot of resources for maintain. For example simple situation - new version of native widgets api and a lot of things needs be rewritten and tested again.

My proposal is add to ability to implement native controls (as external platform).

> Support for that app will be more complicated too (example: casual people often don't know what system they have and then try explain how to open file when file dialog looks different on different platforms).

I am isn't understan this case

> Native widgets on different platforms has its own limitations so you need implement/maintain a list of features that are cross platform and emulate some thing on others.

Trying to implement this will not cost anything for dlangui community if native platform will be added as external.

**Comment by and3md** [comment]
> I am isn't understand this case with file dialog

I have just too big experience with users and theirs problems ;) Open files and lost files is very frequent software support case.

**Comment by denizzzka** [comment]
I am not GUI guru :-)
I just can't understand this case with file open dialogs

**Comment by and3md** [comment]
>I just can't understand this case with file open dialogs

When user of your multiplatform app calls to you and ask "How to open file?" or "Where are my files?" 
Is it simpler to answer when file dialog in your app looks the same on all platform. 

The same with other app functions. When your app looks the same on platform A and B its easier to explain someone how to do something in your app. You don't need ask "What platform you use?"

Creating docs its easier too. So for me not native widgets have advantages.

**Comment by denizzzka** [comment]
> When user of your multiplatform app calls to you and ask "How to open file?" or "Where are my files?"
It's simpler to answer when file dialog in your app looks the same on all platform.

Why?! File open dialog it is just file open dialog.

**Comment by and3md** [comment]
That's why programmers are bad testers :) For you it's easy but not for all. For some users using files is difficult. And when you start help you need first know is it Windows 10? Windows XP? Linux? or MacOS? Because it looks different you can't just say "click second icon on left panel then go to xyz folder". That's only example but from real life :)

BTW. When you want 100% native look&feel maybe better is just use native widgets. Cross platform solution will always do something in other way. So it can be 99,999999% but never 100% native look&feel.

Or better make you own theme that will looks attractive/marketable for your users on all platforms. See how anti viruses software look:) Native widgets look is not "sexy" these days.

**Comment by denizzzka** [comment]
> That's why programmers are bad testers :) For you it's easy but not for all. For some users using files is difficult. And when you start help you need first know is it Windows 10? Windows XP? Linux? or MacOS? 

Why this is important? I heard that some systems (ios) isn't allow users to work with files. In this case we can just leave `assert(0)` at base Widget class and isn't implement native control for it.

> Because it looks different you can't just say "click second icon on left panel then go to xyz folder". 

I don't understan what do you mean

> BTW. When you want 100% native look&feel maybe better is just use native widgets.

This is same as I am propose!

> Cross platform solution will always do something in other way. So it can be 99,999999% but never 100% native look&feel.

But currently dlangui provides only 80% look&feel from native.

**Comment by FreeSlave** [comment]
File dialog is a special thing. I actually would prefer dlangui to provide option to create a native dialog on Windows and OSX. (Linux and other freedesktops don't have native one)

The problem with native widgets in general is that it's harder to get the same behavior on all platforms, it also means additional maintenance cost. And the last one - I guess dlangui just was not planned to support native widgets from the start.

Actually dlangui has many other problems right now. And I would not consider native widgets as high priority.

**Comment by denizzzka** [comment]
> Linux and other freedesktops don't have native one

Linuxes have excellent KDE and GTK file dialogs: with previews, path line search, mkdir, etc

**Comment by denizzzka** [comment]
Maybe it will be useful to extract abstract windows-layouts-widgets engine from dlangui with ability to use it separate from dlangui? I just realized that I really just like this thing which automatically arranges widgets on windows.

**Comment by buggins** [comment]
Probably method like Platform.showFileDialog() may be useful.
For some platforms, it can be implemented using native dialogs.
Native dialogs and native widgets are different things.
Dialogs are much easier to implement than widgets.

**Comment by buggins** [comment]
Closing.
Probably it makes sense to create issue for implementing native dialogs for some platforms.

**Comment by denizzzka** [comment]
For future googlers: it is possible to implement full widgets hierarchy (with addition of any custom widgets) by using native OS components. Just use external platform implementation with addition of custom methods to dlangui widgets by `openmathods`.

More details you can found in https://github.com/denizzzka/formoshlep source
