### ISSUE TITLE
Can build on Android ?

### ISSUE THREAD

**Issue by zoujiaqing** [buggins/dlangui#73]
Hello :)

I want use android's NDK build dlangui, need help.

thanks.

**Comment by buggins** [comment]
Depends on D compiler support.
http://forum.dlang.org/thread/qnxxwaezsrlhqlpwutby@forum.dlang.org

Once someone is managed to get D code compiled with NDK, I can make Android backend for DlangUI.

Although, additional changes will be necessary to add Touch mode support (currently, UI is mouse oriented; for touch mode lists must be scrolled by dragging instead of scrollbars).
