### ISSUE TITLE
Widgets taking keyboard dont get alt graphic keys

### ISSUE THREAD

**Issue by BBasile** [buggins/dlangui#93]
the editors don't take the `~#{[|\^@]}¤` chars. (<kbd>AltGr</kbd>+<kbd>"'(-è_çà)=$</kbd>)
french layout, AZERTY, dlangui master, win7.

tested on DML edit then verified in the other samples...they are not handled.

**Comment by BBasile** [comment]
By the way, among the 38 followers, not any other frenchs ? i can't believe i'm the first to find this bug !

I've compiled dlgui with -d + the debug identifier used to catch key event.
added an the function to redirect the Log to stdout. when typing
- <kbd>AltGr</kbd>: i get a log line for the modifier, ok
- <kbd>AltGr</kbd>+<kbd>'</kbd>: blank log line
then when i release the keys,
- <kbd>'</kbd> released, <kbd>AltGr</kbd> still held: blank log line
- <kbd>AltGr</kbd> released, i get a log line for the modifier.

**Comment by theyamo** [comment]
I have the same issue. AltGr-<key> gets skipped in the text editor. The condition that checks and skips key input when alt is pressed is at editors.d, around line 1417:
```
	if (event.action == KeyAction.Text && event.text.length && !(event.flags & (KeyFlag.Control | KeyFlag.Alt))) {
```
Changing this to check only for the left alt does not work. It seems that event.flags contains wrong information about pressed modifier keys. On Linux at least.

**Comment by Blumerline** [comment]
Me too. The thing is that the french layout (AZERTY) is not widely used (France and a few African countries), most of the countries whose the native language uses a derived form of the latin alphabet use a QWERTY layout, so UTF8 characters over 1 byte can be typed using SHIFT and not ALTGR (like the German umlaut iirc). Even languages that are based on a completly different alphabet use an adapted mapping of QWERTY (Cyrillic: querty, Hebrew: qwerty, etc).

I think this is an SDL backend problem. I cant say how many game using SDL for the windowing and the events have issues with default key strokes assignation because of this (typically qzds).

So the bug is not fixed at all.
